import { url } from "inspector";
import React from "react";
import ReactDomServer from "react-dom/server";

/**
 * This class provides the functions needed to produce the autogenerated survey XML document that
 * the mechanical turk API requires.
 */
class SurveyGenerator {
  /**
   * The XML header of the document that the Mechanical Turk API requires.
   */
  xmlHeader = `
  <HTMLQuestion xmlns="http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2011-11-11/HTMLQuestion.xsd">
    <HTMLContent>
        <![CDATA[<!DOCTYPE html>`;

  /**
   * The XML footer of the autogenerated document.
   */
  xmlFooter = `]]></HTMLContent><FrameHeight>450</FrameHeight></HTMLQuestion>`;

  /**
   * Uses React to convert React-based html elements into an HTML string that is stored in the HTMLContent
   * element of the XML document.
   *
   * @param {array} questions list contianing every question to be added to the autogenerated survey from
   * the Create  component.
   * @param {string} questionDescription string containing the description/explaination that is to be adde
   * before each question in the autogenerated document.
   * @param {boolean} randomizeControlOrder boolean, that if true, will randomize the control/experimental
   * left and right sideness. This is given from user input in the Create component
   * @param {boolean} isPreview boolean that is defaulted to false. If it is true, it will change the auto-
   * generated URL document to remove javascript that is used by Mechanical turk. This is used to produce
   * an HTML document for previewing purposes only.
   *
   * @returns {string} The HTML string of the autogenerated survey
   */
  getHTML = (
    questions,
    questionDescription,
    randomizeControlOrder,
    isPreview = false
  ) => {
    const rawScriptString =
      "for(var i = 0; i < " +
      questions.length +
      '; i ++) {for(var n = 0; n < document.forms["mturk_form"]["question"+1].length; n ++) {document.forms["mturk_form"]["question" + i][n].onclick = validate;}}function validate() {var valid = true;for(var i = 0; i < ' +
      questions.length +
      '; i ++) {if(document.forms["mturk_form"]["question" + i].value == "") {valid = false;}}if(valid) {var button = document.getElementById("submitButton");button.disabled = false;button.value = "Submit";}}';

    return ReactDomServer.renderToString(
      <html>
        <head>
          <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8" />
          <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossOrigin="anonymous"
          />
          {!isPreview && (
            <script
              type="text/javascript"
              src="https://s3.amazonaws.com/mturk-public/externalHIT_v1.js"
            />
          )}
        </head>
        <body>
          <div className="mx-2 my-2">
            <h2 className="border-bottom my-3">Instructions</h2>
            <ul className="text-info">
              <li>Answer each question below</li>
              <li>
                When all questions are answered, click the "Submit" button
              </li>
            </ul>
            <h2 className="border-bottom my-3">Questions</h2>
            <form
              name="mturk_form"
              method="post"
              id="mturk_form"
              action={
                isPreview ? null : "https://www.mturk.com/mturk/externalSubmit"
              }
            >
              <input
                type="hidden"
                value=""
                name="assignmentId"
                id="assignmentId"
              />
              {this.getQuestions(
                questions,
                questionDescription,
                randomizeControlOrder
              )}
              <input
                className="btn btn-primary mb-2"
                type="submit"
                id="submitButton"
                value="You must answer all questions"
                disabled
              />
            </form>
            <script dangerouslySetInnerHTML={{ __html: rawScriptString }} />
          </div>
          {!isPreview && (
            <script language="Javascript">turkSetAssignmentID();</script>
          )}
        </body>
      </html>
    );
  };

  /**
   * Returns the HTML elements that contain the content provided by the given URL
   * @param {string} url the URL to retrieve and wrap into an iframe if it is a youtube video.
   * or a img if it is an image.
   */
  getURLContent = url => {
    const videoURLRegex = /youtu(be\.com|\.be)\/(watch\?v=|embed)?\/?([a-zA-Z0-9_-]+)(&.*)?/;
    const youtubeMatchURL = videoURLRegex.exec(url);
    const isYoutubeURL = youtubeMatchURL != null;
    if (isYoutubeURL) {
      const urlYoutubeID = youtubeMatchURL[3];
      return {
        type: "video",
        embed: (
          <div className="embed-responsive embed-responsive-16by9">
            <iframe
              src={
                "https://www.youtube-nocookie.com/embed/" +
                urlYoutubeID +
                "?modestbranding=0&rel=0&showinfo=0"
              }
              frameBorder="0"
              allow="encrypted-media"
              allowFullScreen={true}
            />
          </div>
        )
      };
    } else {
      return {
        type: "image",
        embed: <img className="img-fluid" src={url} />
      };
    }
  };

  /**
   * Returns the checkbox html elements for each question
   *
   * @param {number} index the question index of the radio button
   * @param {string} type string that defines what type of media the radio button is associated
   * (ie. "video","image")
   * @param {boolean} isLeft boolean that defines whether or not the checkbox is associated with the
   * left or right side of the question content.
   * @param {boolean} isControl boolean that defines whether or not the checkbox is for the control
   * content or the experimental content.
   */
  getRadioButton = (index, type, isLeft, isControl) => {
    return (
      <div className="form-check text-center mt-2">
        <input
          className="form-check-input"
          type="radio"
          name={"question" + index}
          value={isControl ? "c" : "e"}
        />
        <label className="form-check-label">
          {isLeft ? "Left" : "Right"} {type}
        </label>
      </div>
    );
  };

  /**
   * Returns a new question card HTML element for a single URL question
   *
   * @param {*} question the question object that contains the content URL associated with the question
   * @param {number} index the unique question index
   */
  getSingleURLQuestion = (question, index) => {
    const questionContent = this.getURLContent(question.urls[0]);
    return (
      <div>
        {questionContent.embed}
        <div className="row">
          <div className="col-sm">
            {this.getRadioButton(
              index,
              questionContent.type,
              true,
              question.isControlLeft
            )}
          </div>
          <div className="col-sm">
            {this.getRadioButton(
              index,
              questionContent.type,
              false,
              !question.isControlLeft
            )}
          </div>
        </div>
      </div>
    );
  };

  /**
   * Returns a new question card HTML element for a two URL question
   *
   * @param {*} question the question object that contains the two content URLs associated with the question
   * @param {number} index the unique question index
   * @param {boolean} randomizeControlOrder if true, the order of the experimental/control URLs (either left
   * or right side)is randomized.
   */
  getTwoURLQuestion = (question, index, randomizeControlOrder) => {
    const urls = question.urls;
    let leftQuestionContent = this.getURLContent(urls[0]);
    let rightQuestionContent = this.getURLContent(urls[1]);
    let isControlLeft = true;

    if (randomizeControlOrder) {
      console.log("Here");
      if (Math.random() >= 0.5) {
        const tmp = rightQuestionContent;
        rightQuestionContent = leftQuestionContent;
        leftQuestionContent = tmp;
        isControlLeft = false;
      }
    }

    return (
      <div className="row">
        <div className="col-sm">
          {leftQuestionContent.embed}
          {this.getRadioButton(
            index,
            leftQuestionContent.type,
            true,
            isControlLeft
          )}
        </div>
        <div className="col-sm">
          {rightQuestionContent.embed}
          {this.getRadioButton(
            index,
            rightQuestionContent.type,
            false,
            !isControlLeft
          )}
        </div>
      </div>
    );
  };

  /**
   * Gets all of the question HTML elements
   *
   * @param {array} questions list containing every question object (from the Create component)
   * @param {string} questionDescription string containing the description/explaination that is to be adde
   * before each question in the autogenerated document.
   * @param {boolean} randomizeControlOrder if true, the order of the experimental/control URLs (either left
   * or right side)is randomized.
   */
  getQuestions = (questions, questionDescription, randomizeControlOrder) => {
    console.log("2. " + randomizeControlOrder);
    let htmlQuestions = questions.map((question, index) => {
      return (
        <div key={index} className="card my-2 mx-5">
          <div className="card-body">
            <div className="card-title">
              <h4>
                <strong>Question {index + 1}:</strong>
                {" " + questionDescription}
              </h4>
            </div>
            <div className="container">
              {question.urls.length == 1
                ? this.getSingleURLQuestion(question, index)
                : this.getTwoURLQuestion(
                    question,
                    index,
                    randomizeControlOrder
                  )}
            </div>
          </div>
        </div>
      );
    });
    return htmlQuestions;
  };

  /**
   * Returns the autogenerated HTML document for preview purposes
   *
   * @param {array} questions list containing every question object (from the Create component)
   * @param {string} questionDescription string containing the description/explaination that is to be adde
   * before each question in the autogenerated document.
   * @param {boolean} randomizeControlOrder if true, the order of the experimental/control URLs (either left
   * or right side)is randomized.
   *
   * @returns {string} the HTML string representation of the autogenerated survey for preview purposes.
   */
  getPreviewDocument = (
    questions,
    questionDescription,
    randomizeControlOrder
  ) => {
    console.log("1. " + randomizeControlOrder);
    return this.getHTML(
      questions,
      questionDescription,
      randomizeControlOrder,
      true
    );
  };

  /**
   * Gets the autogenerated XML document for publishing to mechanical turk
   *
   * @param {array} questions list containing every question object (from the Create component)
   * @param {string} questionDescription string containing the description/explaination that is to be adde
   * before each question in the autogenerated document.
   * @param {boolean} randomizeControlOrder if true, the order of the experimental/control URLs (either left
   * or right side)is randomized.
   *
   * @returns {string} The string representation of the XML document containing the autogenerated survey
   */
  getDocument = (questions, questionDescription, randomizeControlOrder) => {
    return (
      this.xmlHeader +
      this.getHTML(questions, questionDescription, randomizeControlOrder) +
      this.xmlFooter
    );
  };
}

export default SurveyGenerator;
